### PR TITLE
Added swallow programming language

### PR DESCRIPTION
**Pull request by SaptakBhoumik**
Added a description and link to swallow programming language

### CODE REVIEW

**Comment by SaptakBhoumik** [comment]
@prathyvsh Please note that it is made by me and my friends

**Comment by prathyvsh** [comment]
Is there a documentation where I can read more about what is unique to the language and a page where I can play with the code?

**Comment by SaptakBhoumik** [comment]
@prathyvsh well here is a blog post about it  https://dev.to/saptakbhoumik/swallow-a-new-programming-language-with-python-like-syntax-but-as-fast-as-c-currently-under-devolopment-2of4/

**Comment by SaptakBhoumik** [comment]
@prathyvsh did you read it?

**Comment by prathyvsh** [comment]
> 
> 
> @prathyvsh did you read it?

Hi, yes. Please provide a more detailed documentation page as I think that would be helpful to evaluate the language.

**Comment by SaptakBhoumik** [comment]
> > @prathyvsh did you read it?
> 
> Hi, yes. Please provide a more detailed documentation page as I think that would be helpful to evaluate the language.

I am sorry but the docs are still not complete

**Comment by SaptakBhoumik** [comment]
github -> https://github.com/Swallow-lang/swallow

**Comment by prathyvsh** [comment]
> 
> 
> github repo -> https://github.com/Swallow-lang/swallow

Cool. No worries. Ping back when the documentation is ready, would love to take a closer look at the language.

**Pull request closed without merging**
